name: dog food - tests

on: [push, pull_request, pull_request_target, workflow_dispatch]

permissions:
  contents: read
  security-events: write

# Allow one concurrent deployment
concurrency:
  group: ${{ format('{0}-{1}-{2}-{3}-{4}', github.workflow, github.event_name, github.ref, github.base_ref, github.head_ref) }}
  cancel-in-progress: true

jobs:
  ghdiag:
    name: Run GitHub diagnostic
    if: ${{ vars.ACTIONS_RUNNER_DEBUG || vars.ACTIONS_STEP_DEBUG }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          script: |
            core.debug('!!! START github START !!!')
            core.info(JSON.stringify(github, null, '  '))
            core.debug('!!! END github END !!!')

            core.debug('!!! START context START !!!')
            core.info(JSON.stringify(context, null, '  '))
            core.debug('!!! END context END !!!')
      - run: printenv

  gitleaks:
    runs-on: ubuntu-latest
    name: Run Gitleaks
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        id: gitleaks
        uses: ./
        with:
          report_format: sarif
          fail: false

      - name: Get the output from the gitleaks step
        run: |
          echo "exitcode: ${GITLEAKS_EXITCODE}"
          echo "result: ${GITLEAKS_RESULT}"
          echo "command: ${GITLEAKS_COMMAND}"
          echo "report: ${GITLEAKS_REPORT}"
          echo "output: ${GITLEAKS_OUTPUT}"
        env:
          GITLEAKS_EXITCODE: ${{ steps.gitleaks.outputs.exitcode }}
          GITLEAKS_RESULT: ${{ steps.gitleaks.outputs.result }}
          GITLEAKS_COMMAND: ${{ steps.gitleaks.outputs.command }}
          GITLEAKS_REPORT: ${{ steps.gitleaks.outputs.report }}
          GITLEAKS_OUTPUT: ${{ steps.gitleaks.outputs.output }}

      - name: Upload SARIF report
        if: ${{ steps.gitleaks.outputs.exitcode == 1 }}
        uses: github/codeql-action/upload-sarif@42947a340483f03ba47bb1a039b2c519aab3df85 # v3
        with:
          sarif_file: ${{ steps.gitleaks.outputs.report }}
